--------------------------------------------------------
--  File created - Thursday-April-06-2017   
--------------------------------------------------------
REM INSERTING into HEXICLOUD.PLACEHOLDERS
SET DEFINE OFF;
Insert into HEXICLOUD.PLACEHOLDERS (PLACEHOLDER_CODE,PLACEHOLDER_DESCRIPTION,JOB_ID) values ('<<SR_ID>>','EMAIL REQUEST ID',1);
Insert into HEXICLOUD.PLACEHOLDERS (PLACEHOLDER_CODE,PLACEHOLDER_DESCRIPTION,JOB_ID) values ('<<FIRST_NAME>>','CSM FIRST NAME',1);
Insert into HEXICLOUD.PLACEHOLDERS (PLACEHOLDER_CODE,PLACEHOLDER_DESCRIPTION,JOB_ID) values ('<<LAST_NAME>>','CSM LAST NAME',1);
Insert into HEXICLOUD.PLACEHOLDERS (PLACEHOLDER_CODE,PLACEHOLDER_DESCRIPTION,JOB_ID) values ('<<REMINDER_COUNT>>','CSM REMINDER COUNT',1);
Insert into HEXICLOUD.PLACEHOLDERS (PLACEHOLDER_CODE,PLACEHOLDER_DESCRIPTION,JOB_ID) values ('<<PASSWORD>>','Password',4);
Insert into HEXICLOUD.PLACEHOLDERS (PLACEHOLDER_CODE,PLACEHOLDER_DESCRIPTION,JOB_ID) values ('<<USER_ID>>','User ID',4);
