ALTER TABLE USER_NAVIGATION_AUDIT MODIFY CREATED_DATE TIMESTAMP(6) not null;

ALTER TABLE USER_NAVIGATION_AUDIT ADD (STEP_ID NUMBER not null, ACTION VARCHAR(400));

ALTER TABLE USER_NAVIGATION_AUDIT DROP CONSTRAINT USER_NAVIGATION_AUDIT_FK1;

ALTER TABLE USER_NAVIGATION_AUDIT ADD FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);
