--------------------------------------------------------
--  DDL for Package PKG_USER_NAV_AUDIT
--------------------------------------------------------

create or replace PACKAGE PKG_USER_NAV_AUDIT IS
 PROCEDURE PRC_SAVE_USER_NAV_AUDIT(IN_USER_ID IN USER_NAVIGATION_AUDIT.USER_ID%TYPE,
									IN_STEP_ID IN STEPS.STEP_ID%TYPE,
                  IN_CUR_STEP_LABEL STEPS.STEP_CODE%TYPE,
									IN_ACTION IN USER_EMAILS.MESSAGE%TYPE);
END PKG_USER_NAV_AUDIT;

/

create or replace PACKAGE BODY PKG_USER_NAV_AUDIT
IS
  PROCEDURE PRC_SAVE_USER_NAV_AUDIT(IN_USER_ID IN USER_NAVIGATION_AUDIT.USER_ID%TYPE,
									IN_STEP_ID IN STEPS.STEP_ID%TYPE,
									IN_CUR_STEP_LABEL STEPS.STEP_CODE%TYPE,
									IN_ACTION IN USER_EMAILS.MESSAGE%TYPE)
  IS

    ON_BOARD_COMPLETION_EMAIL_SENT VARCHAR2(1):= 'N';
    USER_EMAIL USERS.EMAIL%TYPE := '';
    USER_FIRST_NAME  USERS.FIRST_NAME%TYPE:= '';
    MESSAGE VARCHAR2(8000) :='';
    SUBJECT VARCHAR2(600) :='';
    email_success VARCHAR2(1)         := 'N';
	PORTAL_NOTIF_EMAIL VARCHAR2(80) := '';
  --    LAST_STEP_LOGGED_DATE	VARCHAR2(10) := '';  
--    LAST_NAV_AUDIT_ENTRY_DATE	VARCHAR2(10) := '';
--    LAST_NAV_ID   USER_NAVIGATION_AUDIT.NAV_ID%TYPE := 0;
--    LAST_NAV_AUDIT_ENTRY_STR 	USER_NAVIGATION_AUDIT.USER_NAV_TRAIL%TYPE  := '';
 
--    CURSOR C_LAST_STEP_LOGGED
--    IS
--      SELECT TO_CHAR(UPDATED_DATE, 'YYYY/MM/DD') 
--      FROM USER_STEPS 
--      WHERE USER_ID = IN_USER_ID;
	  
	  
--    CURSOR C_LAST_NAV_TRAIL_ENTRY
--    IS
--      SELECT TO_CHAR(UPDATED_DATE, 'YYYY/MM/DD'), NAV_ID
--      FROM USER_NAVIGATION_AUDIT 
--      WHERE USER_ID = IN_USER_ID AND ROWNUM = 1 ORDER BY NAV_ID DESC;
	
--    CURSOR C_LAST_NAV_TRAIL_ENTRY_STR
--    IS
--      SELECT USER_NAV_TRAIL 
--      FROM USER_NAVIGATION_AUDIT 
--     WHERE NAV_ID = LAST_NAV_ID;
	  
  BEGIN
  
--	 OPEN C_LAST_STEP_LOGGED;
--      FETCH C_LAST_STEP_LOGGED INTO LAST_STEP_LOGGED_DATE;
--      CLOSE C_LAST_STEP_LOGGED;
      
--	OPEN C_LAST_NAV_TRAIL_ENTRY;
--		FETCH C_LAST_NAV_TRAIL_ENTRY INTO LAST_NAV_AUDIT_ENTRY_DATE, LAST_NAV_ID;
--    CLOSE C_LAST_NAV_TRAIL_ENTRY;
	
--	IF LAST_STEP_LOGGED_DATE = LAST_NAV_AUDIT_ENTRY_DATE THEN
--		OPEN C_LAST_NAV_TRAIL_ENTRY_STR;
--			FETCH C_LAST_NAV_TRAIL_ENTRY_STR INTO LAST_NAV_AUDIT_ENTRY_STR;
--		CLOSE C_LAST_NAV_TRAIL_ENTRY_STR;
		
--		LAST_NAV_AUDIT_ENTRY_STR := LAST_NAV_AUDIT_ENTRY_STR || '|' || IN_STEP_LABEL || ':' || IN_ACTION;
		
--		UPDATE USER_NAVIGATION_AUDIT SET USER_NAV_TRAIL = LAST_NAV_AUDIT_ENTRY_STR, UPDATED_DATE = SYSDATE WHERE NAV_ID = LAST_NAV_ID;
--	ELSE
--		LAST_NAV_AUDIT_ENTRY_STR := IN_STEP_LABEL || ':' || IN_ACTION;
		INSERT INTO USER_NAVIGATION_AUDIT (USER_ID, STEP_ID, ACTION, CREATED_DATE) VALUES (IN_USER_ID, IN_STEP_ID, IN_ACTION, SYSDATE);
--	END IF;
	
	IF IN_CUR_STEP_LABEL = 'dashboard' THEN
	

		BEGIN
			SELECT COMPLETION_EMAIL_SENT INTO ON_BOARD_COMPLETION_EMAIL_SENT
			FROM USER_PHASE_COMPLETETION 
			WHERE USER_ID = IN_USER_ID AND PHASE = 'onboarding';
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
		  ON_BOARD_COMPLETION_EMAIL_SENT := 'N';
		END;
		
		IF ON_BOARD_COMPLETION_EMAIL_SENT = 'N' THEN

		  SELECT EMAIL, FIRST_NAME   INTO USER_EMAIL, USER_FIRST_NAME
		  FROM USERS 
		  WHERE USER_ID = IN_USER_ID;
      
		  SELECT RULE_VALUE INTO SUBJECT FROM RULE_CONFIGURATION WHERE RULE_KEY = 'ON_BOARDING_COMPLETION_EMAIL_SUBJECT';
		  SELECT RULE_VALUE INTO MESSAGE FROM RULE_CONFIGURATION WHERE RULE_KEY = 'ON_BOARDING_COMPLETION_EMAIL_BODY';
		  SELECT RULE_VALUE INTO PORTAL_NOTIF_EMAIL FROM RULE_CONFIGURATION WHERE RULE_KEY = 'PORTAL_NOTIFICATION_EMAIL_ID';

			MESSAGE := REPLACE(MESSAGE, '<<FIRST_NAME>>', USER_FIRST_NAME);
			
			send_email(PORTAL_NOTIF_EMAIL, USER_EMAIL, SUBJECT, MESSAGE, email_success);
			IF email_success = 'Y' THEN
			 INSERT INTO USER_PHASE_COMPLETETION (USER_ID, PHASE, COMPLETED_DATE, COMPLETION_EMAIL_SENT, SENT_EMAIL_COUNT) VALUES (IN_USER_ID, 'onboarding', SYSDATE, 'Y', 1);
			END IF;
			
		END IF;
			
	
	END IF;
   COMMIT;
    
  END PRC_SAVE_USER_NAV_AUDIT;
END PKG_USER_NAV_AUDIT;