DELETE FROM USER_NAVIGATION_AUDIT;

REM INSERTING into STEPS
SET DEFINE OFF;

Insert into STEPS (STEP_ID,STEP_CODE,DESCRIPTION,IS_ROLE_SELELCTION,IS_DECISION_MAKING,NON_REDIRECT_STEP,STEP_LABEL,HAS_SUB_STEP,SUB_STEP_LABEL) values (16,'logout','Logout from the portal',0,0,0,'Logout from Portal','N',null);
Insert into STEPS (STEP_ID,STEP_CODE,DESCRIPTION,IS_ROLE_SELELCTION,IS_DECISION_MAKING,NON_REDIRECT_STEP,STEP_LABEL,HAS_SUB_STEP,SUB_STEP_LABEL) values (17,'useCases','Get more out of Oracle Cloud',0,0,0,'Use cases page','N',null);
Insert into STEPS (STEP_ID,STEP_CODE,DESCRIPTION,IS_ROLE_SELELCTION,IS_DECISION_MAKING,NON_REDIRECT_STEP,STEP_LABEL,HAS_SUB_STEP,SUB_STEP_LABEL) values (18,'faqs','Cloud Get Started - FAQ''s',0,0,0,'Resources page','N',null);

COMMIT;
